"""add_phase_4_modules

Revision ID: b09ddf082b28
Revises: d240545ba046
Create Date: 2026-03-31 00:53:57.142812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09ddf082b28'
down_revision: Union[str, Sequence[str], None] = 'd240545ba046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['hr_employees.id'], name='fk_dept_manager', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_departments_tenant_id'), 'hr_departments', ['tenant_id'], unique=False)
    op.create_table('hr_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hr_departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_hr_employees_tenant_id'), 'hr_employees', ['tenant_id'], unique=False)
    op.create_table('lms_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_courses_tenant_id'), 'lms_courses', ['tenant_id'], unique=False)
    op.create_table('pm_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_projects_tenant_id'), 'pm_projects', ['tenant_id'], unique=False)
    op.create_table('hr_time_off_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_time_off_requests_tenant_id'), 'hr_time_off_requests', ['tenant_id'], unique=False)
    op.create_table('lms_course_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_course_modules_tenant_id'), 'lms_course_modules', ['tenant_id'], unique=False)
    op.create_table('lms_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_enrollments_tenant_id'), 'lms_enrollments', ['tenant_id'], unique=False)
    op.create_table('mrp_boms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('product_qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrp_boms_tenant_id'), 'mrp_boms', ['tenant_id'], unique=False)
    op.create_table('pm_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pm_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_tasks_tenant_id'), 'pm_tasks', ['tenant_id'], unique=False)
    op.create_table('mrp_bom_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bom_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('product_qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['mrp_boms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrp_bom_lines_tenant_id'), 'mrp_bom_lines', ['tenant_id'], unique=False)
    op.create_table('mrp_production_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('bom_id', sa.UUID(), nullable=True),
    sa.Column('product_qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_planned_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_planned_finished', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['mrp_boms.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrp_production_orders_tenant_id'), 'mrp_production_orders', ['tenant_id'], unique=False)
    op.create_table('pm_timesheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['pm_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_timesheets_tenant_id'), 'pm_timesheets', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pm_timesheets_tenant_id'), table_name='pm_timesheets')
    op.drop_table('pm_timesheets')
    op.drop_index(op.f('ix_mrp_production_orders_tenant_id'), table_name='mrp_production_orders')
    op.drop_table('mrp_production_orders')
    op.drop_index(op.f('ix_mrp_bom_lines_tenant_id'), table_name='mrp_bom_lines')
    op.drop_table('mrp_bom_lines')
    op.drop_index(op.f('ix_pm_tasks_tenant_id'), table_name='pm_tasks')
    op.drop_table('pm_tasks')
    op.drop_index(op.f('ix_mrp_boms_tenant_id'), table_name='mrp_boms')
    op.drop_table('mrp_boms')
    op.drop_index(op.f('ix_lms_enrollments_tenant_id'), table_name='lms_enrollments')
    op.drop_table('lms_enrollments')
    op.drop_index(op.f('ix_lms_course_modules_tenant_id'), table_name='lms_course_modules')
    op.drop_table('lms_course_modules')
    op.drop_index(op.f('ix_hr_time_off_requests_tenant_id'), table_name='hr_time_off_requests')
    op.drop_table('hr_time_off_requests')
    op.drop_index(op.f('ix_pm_projects_tenant_id'), table_name='pm_projects')
    op.drop_table('pm_projects')
    op.drop_index(op.f('ix_lms_courses_tenant_id'), table_name='lms_courses')
    op.drop_table('lms_courses')
    op.drop_index(op.f('ix_hr_employees_tenant_id'), table_name='hr_employees')
    op.drop_table('hr_employees')
    op.drop_index(op.f('ix_hr_departments_tenant_id'), table_name='hr_departments')
    op.drop_table('hr_departments')
    # ### end Alembic commands ###
