"""add system_settings table

Revision ID: e8d0fbb17144
Revises: 2026033121
Create Date: 2026-04-02 03:13:57.471916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8d0fbb17144'
down_revision: Union[str, Sequence[str], None] = '2026033121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'system_settings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('brand_name', sa.String(length=255), nullable=True, server_default='Hatron'),
        sa.Column('logo_url', sa.String(length=500), nullable=True),
        sa.Column('favicon_url', sa.String(length=500), nullable=True),
        sa.Column('footer_text', sa.Text(), nullable=True),
        sa.Column('header_custom_html', sa.Text(), nullable=True),
        sa.Column('payment_settings', sa.JSON(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_tenant_id'), 'system_settings', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.create_foreign_key('sales_orders_contact_id_fkey', 'sales_orders', 'contacts', ['contact_id'], ['id'])
    op.drop_constraint('fk_dept_manager', 'hr_departments', type_='foreignkey')
    op.create_table('pos_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('stop_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('opening_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('closing_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='pos_sessions_tenant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pos_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pos_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_pos_sessions_tenant_id', 'pos_sessions', ['tenant_id'], unique=False)
    op.create_table('pos_order_lines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_subtotal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['pos_orders.id'], name='pos_order_lines_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='pos_order_lines_product_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='pos_order_lines_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pos_order_lines_pkey')
    )
    op.create_index('ix_pos_order_lines_tenant_id', 'pos_order_lines', ['tenant_id'], unique=False)
    op.create_table('pos_orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_reference', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount_total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_tax', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_return', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='pos_orders_contact_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['pos_sessions.id'], name='pos_orders_session_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='pos_orders_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pos_orders_pkey')
    )
    op.create_index('ix_pos_orders_tenant_id', 'pos_orders', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
